name: "Update Web App with FTP"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Deploy Laravel application (exclude everything except mix-manifest.json)
      - name: "Laravel App Deployment"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_LARAVEL_DIR }}
          port: ${{ secrets.FTP_PORT }}

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # 3) Deploy public assets via lftp (and clean Laravel public folder)
      - name: "Deploy Public Assets & Clean Laravel Public"
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -p "$FTP_PORT" "$FTP_HOST" <<EOF
          set ftp:list-options -a
          set cmd:fail-exit yes
          set mirror:parallel-transfer-count 8

          # 1. Mirror local public/ → remote public_html/
          mirror --reverse --delete \
              --exclude-glob mix-manifest.json \
              public/ $FTP_PUBLIC_HTML

          # 2. Clean Laravel public folder (keep only mix-manifest.json)
          cd $FTP_LARAVEL_DIR/public

          # List all files/folders except mix-manifest.json and delete them
          cls -1 | grep -v '^mix-manifest.json$' | while read item; do
            rm -r "$item"
          done

          bye
          EOF
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PUBLIC_HTML: ${{ secrets.FTP_PUBLIC_HTML }}
          FTP_LARAVEL_DIR: ${{ secrets.FTP_LARAVEL_DIR }}
