name: "Update Web App with FTP"

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Deploy Laravel application (exclude everything except mix-manifest.json)
      - name: "Laravel App Deployment"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"
          server-dir: ${{ secrets.FTP_LARAVEL_DIR }}

      # 3) Deploy public assets via lftp (exclude mix-manifest.json)
      - name: "Public Assets Deployment"
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" <<EOF
            # Show hidden files
            set ftp:list-options -a

            # Exit on any error
            set cmd:fail-exit yes

            # Enable parallel transfers (up to 8)
            set mirror:parallel-transfer-count 8

            # Mirror local public/ to remote public_html/, excluding mix-manifest.json
            mirror --reverse --delete \
              --exclude-glob mix-manifest.json \
              public/ $FTP_PUBLIC_HTML

            bye
          EOF
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PUBLIC_HTML: ${{ secrets.FTP_PUBLIC_HTML }}
